export const ERROR_CODE = {
  ERR_DUPLICATED_PHONE_NO: 100001,
  ERR_VERIFY_CODE: 100002,
  ERR_VERIFY_CODE_TIME: 100003,
  NOT_SUPPORT_PHONE_NO: 100004,
  
  ERR_FORMAT_PHONE_NO: 110001,
  ERR_FORMAT_EMAIL: 110002,

  ERR_NULL_PHONE_NO: 120001,
  ERR_NULL_EMAIL: 120002,

  NOT_API: 200001,
  UNKNOW_ERROR: 9999,
};

export const ERROR_MESSAGE = {
  ERR_DUPLICATED_PHONE_NO: '该手机号已注册，请直接登录',
  ERR_VERIFY_CODE: '验证码错误',
  ERR_VERIFY_CODE_TIME: '频繁发送验证码',
  NOT_SUPPORT_PHONE_NO: '暂不支持国际手机号码',

  ERR_FORMAT_PHONE_NO: '手机号码格式错误',
  ERR_FORMAT_EMAIL: '邮箱格式错误',

  ERR_NULL_PHONE_NO: '请填写手机号',
  ERR_NULL_EMAIL: '请填写邮箱',
  
  NOT_API: '没有此 API',
  UNKNOW_ERROR: '未知错误',
};
