export const ERROR_CODE = {
  ERR_DUPLICATED_PHONE_NO: 100001,
  ERR_FORMAT_PHONE_NO: 100002,
  ERR_NULL_PHONE_NO: 100003,
  NOT_SUPPORT_PHONE_NO: 100004,
  NOT_API: 100101,
  UNKNOW_ERROR: 9999,
};

export const ERROR_MESSAGE = {
  ERR_DUPLICATED_PHONE_NO: '该手机号已注册，请直接登录',
  ERR_FORMAT_PHONE_NO: '手机号码格式错误',
  ERR_NULL_PHONE_NO: '请填写手机号',
  NOT_SUPPORT_PHONE_NO: '暂不支持国际手机号码',
  NOT_API: '没有此 API',
  UNKNOW_ERROR: '未知错误',
};
